export default Object.freeze({
	MAIN_APP: 'MAIN_APP',
	WELCOME_SCREEN: 'WELCOME_SCREEN',
	SIGNUP_SCREEN: 'SIGNUP_SCREEN',
	SIGNIN_SCREEN: 'SIGNIN_SCREEN',
	FEED_SCREEN: 'FEED_SCREEN',
	MY_DONATION_SCREEN: 'MY_DONATION_SCREEN',
	ACCOUNT_SCREEN: 'ACCOUNT_SCREEN',
	CARD_DETAILS: 'CARD_DETAILS',
});
